"""Admin2

Revision ID: 1b95761bb93b
Revises: 0ae2056626b4
Create Date: 2025-04-05 13:25:13.408206

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1b95761bb93b'
down_revision = '0ae2056626b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_category')
    op.drop_table('category')
    op.add_column('chat', sa.Column('categories', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('chat', sa.Column('subcategories', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'subcategories')
    op.drop_column('chat', 'categories')
    op.create_table('category',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], name='category_parent_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='category_pkey'),
    sa.UniqueConstraint('name', name='category_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('chat_category',
    sa.Column('chat_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='chat_category_category_id_fkey'),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], name='chat_category_chat_id_fkey'),
    sa.PrimaryKeyConstraint('chat_id', 'category_id', name='chat_category_pkey')
    )
    # ### end Alembic commands ###