"""updates

Revision ID: a5b37678e5f0
Revises: 1b95761bb93b
Create Date: 2025-04-05 14:17:14.719568

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a5b37678e5f0'
down_revision = '1b95761bb93b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('suggestions', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'suggestions')
    # ### end Alembic commands ###